// backend/routes/interactions.js
import { Router } from 'express';
import { requireAuth } from '../middleware/auth.js';
import * as ctrl from '../controllers/interactionsController.js';
const router = Router();
router.post('/toggle_favorite', requireAuth, ctrl.toggleFavorite);
router.post('/record_view', requireAuth, ctrl.recordView);
router.post('/record_download', requireAuth, ctrl.recordDownload);
router.post('/record_daily_visit', requireAuth, ctrl.recordDailyVisit);
router.post('/submit_rating', requireAuth, ctrl.submitRating);
router.post('/like_resource', requireAuth, ctrl.likeResource);
router.post('/comment_resource', requireAuth, ctrl.commentResource);
router.post('/submit_mood', requireAuth, ctrl.submitMood);
router.post('/save_achievement', requireAuth, ctrl.saveAchievement);
router.post('/update_user_presence', requireAuth, ctrl.updateUserPresence);
router.get('/get_resource_interactions', ctrl.getResourceInteractions);
router.get('/get_user_favorites', requireAuth, ctrl.getUserFavorites);
router.get('/get_recent_views', requireAuth, ctrl.getRecentViews);
router.get('/get_user_ratings', requireAuth, ctrl.getUserRatings);
router.get('/get_user_achievements', requireAuth, ctrl.getUserAchievements);
router.get('/get_user_streak', requireAuth, ctrl.getUserStreak);
router.get('/get_public_stats', ctrl.getPublicStats);
router.post('/save_quiz_state', requireAuth, ctrl.saveQuizState);
router.get('/get_quiz_state', requireAuth, ctrl.getQuizState);
router.post('/track_event', requireAuth, ctrl.trackEvent);
router.get('/platform-stats', ctrl.platformStats);
router.get('/dashboard', requireAuth, ctrl.dashboard);
router.get('/daily-challenge', requireAuth, ctrl.dailyChallenge);
router.get('/weak-areas', requireAuth, ctrl.weakAreas);
router.get('/learning-paths', requireAuth, ctrl.learningPaths);
router.get('/personal-records', requireAuth, ctrl.personalRecords);
export default router;
